### ISSUE TITLE
Update WelcomePage and add login/registration functionality 

### ISSUE THREAD

**Issue by DavidZ79** [CSC207-2022F-UofT/course-project-poppin-party-peacocks#60]
GUI:

- [ ] Change JLabels to white CustomJLabels.
- [ ] Remove white corners on the CustomJButtons.
- [ ] Make background gradient (optional, experiment to see if it looks good). See custom JPanel class GradientJPanel.

Functionality:

- [x]  Add login and signup functionality. Note: confirm password field for signup was removed.

Why: GUI needs to be consistent across the entire program, as well as adhere to clean architecture.

Notes: Don't forget to fetch any changes from main if you don't see a file that I mentioned above. See the page navigation reference for how we agreed to navigate between pages.

**Comment by linajin03** [comment]
I can help with functionality!

**Comment by chens408** [comment]
I'll work on the GUI and connect with Lina to resolve this issue :)
