### ISSUE TITLE
Update GUI of AddWishlistPage

### ISSUE THREAD

**Issue by DavidZ79** [CSC207-2022F-UofT/course-project-poppin-party-peacocks#61]
GUI:

- [x] Replicate Figma Design
- [x] Style CustomJButtons similarly to HomePage.
- [x] Black Border around JTextField
- [x] Round the corners of JTextField?
- [x] Integrate Gradient colour scheme

Functionality:
- [ ] #91

Why: GUI needs to be consistent across the entire program, as well as adhere to clean architecture.

Notes: Don't forget to fetch any changes from main if you don't see a file that I mentioned above. See the page navigation reference for how we agreed to navigate between pages.

**Comment by chens408** [comment]
I'll work on the GUI !!
